// src/routes/Picture.tsx
import { useState, useRef, useCallback, useEffect, useMemo } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { removeBackground } from '@imgly/background-removal'
import { track } from '../lib/analytics'
import { useStore } from '../store/useStore'
import FanCard from '../components/FanCard'
import Button from '../components/Button'
import { getTeam } from '../data/teams'
import { getTeamCardBackground } from '../lib/teamCardBackground'
import cameraIcon from '../assets/icons/camera-white.svg'
import chevLeft from '../assets/icons/Chevron-left-white.svg'

// Model files are self-hosted under <origin><base>bg-removal/.
// publicPath must be absolute — the library calls new URL(hash, publicPath) which requires an absolute base.
const BG_REMOVAL_PUBLIC_PATH = window.location.origin + import.meta.env.BASE_URL + 'bg-removal/'

// ─── Image compression ────────────────────────────────────────────────────────
function compressDataUrl(source: HTMLVideoElement | HTMLImageElement, flipX = false): string {
  const sw = source instanceof HTMLVideoElement ? source.videoWidth : source.naturalWidth
  const sh = source instanceof HTMLVideoElement ? source.videoHeight : source.naturalHeight
  const MAX = 480
  const scale = Math.min(MAX / sw, MAX / sh, 1)
  const w = Math.round(sw * scale)
  const h = Math.round(sh * scale)
  const canvas = document.createElement('canvas')
  canvas.width = w
  canvas.height = h
  const ctx = canvas.getContext('2d')!
  if (flipX) { ctx.translate(w, 0); ctx.scale(-1, 1) }
  ctx.drawImage(source, 0, 0, w, h)
  return canvas.toDataURL('image/jpeg', 0.78)
}

// ─── Silhouette SVG — full body, position absolute, bottom-aligned ────────────
function SilhouettePlaceholder() {
  return (
    <svg
      className="picture-silhouette-svg"
      width="364"
      height="418"
      viewBox="0 0 364 418"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      style={{ position: 'absolute', bottom: 0, left: 0, width: '100%', height: 'auto', pointerEvents: 'none', opacity: 0.5 }}
    >
      <path
        d="M17.6249 416.239H136.57L331.854 415.696C337.969 416.872 351.678 417.65 357.596 411.353C363.514 405.056 362.823 394.796 361.738 390.453C359.174 372.811 348.542 334.594 326.528 322.868C241.018 276.454 244.568 271.84 240.13 266.683C235.692 261.526 229.182 250.126 232.437 227.326C234.955 209.684 251.965 194.484 256.995 162.998C258.369 154.4 262.617 139.113 264.984 124.456C266.869 112.785 259.658 110.07 256.404 103.556C258.475 65.5565 254.628 57.9566 251.078 49.5424C247.527 41.1282 229.774 1.5 180.657 1.5C131.54 1.5 116.746 36.7854 108.461 49.5424C101.834 59.748 104.319 95.2324 106.39 111.699C94.2589 114.142 98.6116 128.305 106.39 162.998C114.971 201.269 127.102 217.284 128.877 227.326C130.016 233.768 131.325 254.359 122.368 266.683C113.491 278.897 83.0153 302.24 56.9775 313.097C29.5619 324.528 13.088 351.187 8.74836 364.125C4.90186 373.896 -1.60759 395.61 3.12656 404.296C7.86071 412.982 14.7647 415.877 17.6249 416.239Z"
        fill="white"
        fillOpacity="0.5"
        stroke="#DBDEE8"
        strokeWidth="3"
        strokeLinecap="round"
        strokeDasharray="8 8"
      />
    </svg>
  )
}

// ─── Progress bar ─────────────────────────────────────────────────────────────
function ProgressBar({ progress }: { progress: number }) {
  return (
    <div className="picture-progress-track"
      style={{
        flex: 1,
        height: 8,
        borderRadius: 'var(--f-brand-radius-rounded)',
        background: 'var(--f-brand-color-border-default)',
        overflow: 'hidden',
      }}
    >
      <div className="picture-progress-fill"
        style={{
          width: `${progress}%`,
          height: '100%',
          borderRadius: 'var(--f-brand-radius-rounded)',
          background: 'linear-gradient(-90deg, var(--f-brand-color-border-success) 61.5%, var(--f-brand-color-background-success) 100%)',
          boxShadow: 'var(--f-brand-shadow-medium)',
          transition: `width var(--f-brand-motion-duration-quick) var(--f-brand-motion-easing-exit)`,
        }}
      />
    </div>
  )
}

// ─── Main Picture route ──────────────────────────────────────────────────────
export default function Picture() {
  const navigate = useNavigate()
  const location = useLocation()
  const { teamId } = (location.state as { teamId: string } | null) ?? { teamId: '' }
  const { state, updateFanCard } = useStore()

  const [photoDataUrl, setPhotoDataUrl] = useState<string | null>(null)
  const [cameraError, setCameraError] = useState<string | null>(null)
  const [removingBg, setRemovingBg] = useState(false)
  const [bgProgress, setBgProgress] = useState(0)
  const [bgError, setBgError] = useState<string | null>(null)

  const processPhoto = useCallback(async (rawDataUrl: string) => {
    setRemovingBg(true)
    setBgProgress(0)
    setBgError(null)
    try {
      const blob = await removeBackground(rawDataUrl, {
        publicPath: BG_REMOVAL_PUBLIC_PATH,
        model: 'small',
        proxyToWorker: false,
        progress: (_key: string, current: number, total: number) => {
          if (total > 0) setBgProgress(Math.round((current / total) * 100))
        },
      })
      const dataUrl = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader()
        reader.onload = () => resolve(reader.result as string)
        reader.onerror = reject
        reader.readAsDataURL(blob)
      })
      setPhotoDataUrl(dataUrl)
      setRemovingBg(false)
      track('picture_bg_removed')
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      console.error('[bg-removal] failed:', err)
      setBgError(msg)
      setPhotoDataUrl(rawDataUrl)
      setRemovingBg(false)
    }
  }, [])

  const videoRef = useRef<HTMLVideoElement>(null)
  const streamRef = useRef<MediaStream | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [cameraActive, setCameraActive] = useState(false)

  // ── Camera lifecycle ─────────────────────────────────────────────────────
  const stopCamera = useCallback(() => {
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(t => t.stop())
      streamRef.current = null
    }
    setCameraActive(false)
  }, [])

  useEffect(() => {
    return () => stopCamera()
  }, [stopCamera])

  useEffect(() => {
    if (cameraActive && streamRef.current && videoRef.current) {
      videoRef.current.srcObject = streamRef.current
      videoRef.current.play().catch(() => {})
    }
  }, [cameraActive])

  const startCamera = useCallback(async () => {
    setCameraError(null)
    if (!navigator.mediaDevices?.getUserMedia) {
      fileInputRef.current?.click()
      return
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'user', width: { ideal: 640 }, height: { ideal: 640 } },
      })
      streamRef.current = stream
      setCameraActive(true)
      track('picture_camera_started')
    } catch {
      setCameraError('Camera unavailable — pick from files instead')
      fileInputRef.current?.click()
    }
  }, [])

  const capturePhoto = useCallback(() => {
    const video = videoRef.current
    if (!video || video.readyState < 2 || !video.videoWidth) return
    const url = compressDataUrl(video, true)
    stopCamera()
    void processPhoto(url)
    track('picture_photo_captured')
  }, [stopCamera, processPhoto])

  const handleFileChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = ev => {
      const img = new Image()
      img.onload = () => {
        const url = compressDataUrl(img)
        void processPhoto(url)
        track('picture_photo_picked')
      }
      img.src = ev.target?.result as string
    }
    reader.readAsDataURL(file)
  }, [])

  const handleTakePhoto = useCallback(() => {
    if (cameraActive) {
      capturePhoto()
    } else {
      startCamera()
    }
  }, [cameraActive, capturePhoto, startCamera])

  const handleRetake = useCallback(() => {
    setPhotoDataUrl(null)
    if (fileInputRef.current) fileInputRef.current.value = ''
    stopCamera()
    track('picture_retake_tapped')
  }, [stopCamera])

  const handleConfirm = useCallback(() => {
    updateFanCard({ photoDataUrl, teamId: teamId || null })
    track('picture_confirmed')
    navigate('/card', { replace: true })
  }, [navigate, updateFanCard, photoDataUrl, teamId])

  const handleBack = useCallback(() => {
    stopCamera()
    navigate(-1)
  }, [navigate, stopCamera])

  // Preview fan card — store data + new photo + teamId
  const previewFanCard = useMemo(() => ({
    ...state.fanCard,
    photoDataUrl,
    teamId: teamId || state.fanCard.teamId,
  }), [state.fanCard, photoDataUrl, teamId])
  const selectedTeam = useMemo(
    () => (teamId ? getTeam(teamId) : state.fanCard.teamId ? getTeam(state.fanCard.teamId) : undefined),
    [teamId, state.fanCard.teamId]
  )
  const teamCardBackground = useMemo(
    () => getTeamCardBackground(selectedTeam?.id ?? ''),
    [selectedTeam?.id]
  )


  const hasPhoto = !!photoDataUrl || removingBg

  return (
    <div className="f-page-enter picture-page"
      data-page="picture"
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        width: '100%',
        background: 'var(--f-brand-color-background-default)',
        overflowY: 'auto',
        WebkitOverflowScrolling: 'touch',
      }}
    >
      {/* ── Top bar: back button + progress ──────────────────── */}
      <div data-section="header" className="picture-header" style={{
        display: 'flex',
        alignItems: 'center',
        gap: 'var(--f-brand-space-md)',
        padding: 'var(--sp-18) var(--f-brand-space-md) 0 var(--f-brand-space-md)',
        flexShrink: 0,
      }}>
        <button className="picture-back-btn"
          data-ui="back-btn"
          onClick={handleBack}
          aria-label="Go back"
          style={{
            width: 'var(--sp-12)',
            height: 'var(--sp-12)',
            borderRadius: 'var(--f-brand-radius-rounded)',
            background: 'var(--f-brand-color-text-light)',
            border: 'none',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            flexShrink: 0,
            boxShadow: 'var(--f-brand-shadow-medium)',
          }}
        >
          <img className="picture-back-icon"
            src={chevLeft}
            width={24}
            height={24}
            alt=""
            style={{ filter: 'brightness(0)' }}
          />
        </button>

        <ProgressBar progress={50} />
      </div>

      {/* ── Title ────────────────────────────────────────────── */}
      <h2 data-section="title" className="picture-title" style={{
        font: 'var(--f-brand-type-title-2)',
        color: 'var(--f-brand-color-text-default)',
        textAlign: 'center',
        marginTop: 'var(--f-brand-space-lg)',
        flexShrink: 0,
      }}>
        Add your picture
      </h2>

      {/* ── Camera / Card preview ────────────────────────────── */}
      {!hasPhoto ? (
        /* Camera */
        <div data-section="camera-preview" className="picture-camera-preview" style={{
          margin: 'var(--f-brand-space-lg) var(--f-brand-space-md) 0',
          background: cameraActive ? 'var(--f-brand-color-text-light)' : 'transparent',
          borderRadius: 'var(--f-brand-radius-small)',
          height: 515,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          position: 'relative',
          overflow: 'hidden',
          flexShrink: 0,
        }}>
          {cameraActive ? (
            <div className="picture-camera-feed" style={{ width: '100%', height: '100%', position: 'relative' }}>
              <video className="picture-camera-video"
                ref={videoRef}
                autoPlay
                playsInline
                muted
                style={{ width: '100%', height: '100%', objectFit: 'cover', transform: 'scaleX(-1)' }}
              />
              <button className="picture-capture-btn"
                data-ui="capture-photo-btn"
                onClick={capturePhoto}
                aria-label="Capture photo"
                style={{
                  position: 'absolute', bottom: 'var(--f-brand-space-xl)', left: '50%', transform: 'translateX(-50%)',
                  width: 'var(--sp-18)', height: 'var(--sp-18)', borderRadius: 'var(--f-brand-radius-rounded)',
                  background: 'none', border: 'var(--c-capture-ring) solid var(--f-brand-color-text-light)',
                  padding: 'var(--sp-1)', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center',
                }}
              >
                <div style={{ width: '100%', height: '100%', borderRadius: 'var(--f-brand-radius-rounded)', background: 'var(--f-brand-color-text-light)' }} />
              </button>
            </div>
          ) : (
            <div style={{
              width: '100%',
              height: '100%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}>
              <div className="picture-team-placeholder-card" style={{
                width: 'auto',
                height: '100%',
                maxWidth: '100%',
                aspectRatio: '5 / 7',
                borderRadius: 'var(--f-brand-radius-outer)',
                background: teamCardBackground,
                backgroundSize: 'cover',
                backgroundPosition: 'center',
                border: '1px solid var(--c-card-border)',
                boxShadow: 'var(--f-brand-shadow-large)',
                position: 'relative',
                overflow: 'hidden',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                padding: 'var(--sp-6) var(--sp-4)',
              }}>
              <div style={{
                position: 'absolute',
                top: 0,
                left: 0,
                right: 0,
                height: 'var(--sp-1)',
                background: 'linear-gradient(90deg, transparent, var(--c-lt-shimmer), transparent)',
              }} />
              <div style={{
                position: 'absolute',
                inset: 0,
                backgroundImage: 'radial-gradient(circle, var(--c-lt-shimmer) 1.5px, transparent 1.5px)',
                backgroundSize: 'var(--sp-4) var(--sp-4)',
                mixBlendMode: 'overlay',
                pointerEvents: 'none',
              }} />
              <div style={{
                position: 'absolute',
                inset: 0,
                backgroundImage: 'repeating-linear-gradient(-55deg, transparent, transparent var(--sp-5), var(--c-lt-shimmer) var(--sp-5), var(--c-lt-shimmer) calc(var(--sp-5) + 1px))',
                mixBlendMode: 'overlay',
                pointerEvents: 'none',
              }} />
              {selectedTeam && (
                <div style={{
                  position: 'absolute',
                  top: 'var(--sp-4)',
                  left: 'var(--sp-4)',
                  right: 'var(--sp-4)',
                  display: 'flex',
                  justifyContent: 'center',
                }}>
                  <div style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: 'var(--sp-2)',
                    padding: 'var(--sp-1) var(--sp-3)',
                    borderRadius: 'var(--f-brand-radius-rounded)',
                    background: 'var(--f-brand-color-background-dark-50a)',
                    color: 'var(--f-brand-color-text-light)',
                    font: 'var(--f-brand-type-subheading-medium)',
                    fontStyle: 'italic',
                  }}>
                    <span aria-hidden="true">{selectedTeam.flag}</span>
                    <span>{selectedTeam.motto}</span>
                  </div>
                </div>
              )}
              <SilhouettePlaceholder />
              <Button
                variant="white-filled"
                className="picture-take-photo-btn"
                data-ui="take-photo-btn"
                onClick={handleTakePhoto}
                style={{
                  position: 'absolute',
                  top: '50%',
                  left: '50%',
                  transform: 'translate(-50%, -50%)',
                  minWidth: 197,
                  minHeight: 'var(--sp-14)',
                  boxShadow: 'var(--f-brand-shadow-large)',
                }}
                iconRight={<img src={cameraIcon} width={20} height={20} alt="" style={{ filter: 'brightness(0)' }} />}
              >
                Take a photo
              </Button>
              </div>
            </div>
          )}
        </div>
      ) : removingBg ? (
        /* BG removal loading */
        <div style={{
          flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center',
          justifyContent: 'center', gap: 'var(--f-brand-space-sm)',
          padding: 'var(--f-brand-space-lg) var(--f-brand-space-md)',
        }}>
          <div style={{
            width: 40, height: 40, borderRadius: '50%',
            border: '3px solid var(--f-brand-color-border-default)',
            borderTopColor: 'var(--f-brand-color-background-primary)',
            animation: 'f-spinner-spin var(--dur-gentle) linear infinite',
          }} />
          <p style={{ font: 'var(--f-brand-type-caption)', color: 'var(--f-brand-color-text-subtle)', margin: 0 }}>
            {bgProgress > 0 && bgProgress < 100 ? `Downloading model ${bgProgress}%…` : 'Removing background…'}
          </p>
          {bgProgress > 0 && bgProgress < 100 && <ProgressBar progress={bgProgress} />}
        </div>
      ) : (
        /* Fan card preview */
        <div data-section="card-preview" style={{
          flex: 1,
          display: 'flex',
          flexDirection: 'column',
          gap: 'var(--f-brand-space-md)',
          padding: 'var(--f-brand-space-md) var(--f-brand-space-md) 0',
          overflowY: 'auto',
          WebkitOverflowScrolling: 'touch',
        }}>
          <FanCard
            fanCard={previewFanCard}
            onSave={() => {}}
          />
        </div>
      )}

      {/* ── Camera error ─────────────────────────────────────── */}
      {cameraError && (
        <p className="picture-camera-error" style={{
          font: 'var(--f-brand-type-caption)', fontSize: 'var(--text-xs)',
          color: 'var(--f-brand-color-status-error)',
          marginTop: 'var(--f-brand-space-xs)', textAlign: 'center',
          padding: '0 var(--f-brand-space-md)',
        }}>
          {cameraError}
        </p>
      )}

      {/* ── Hidden file input ────────────────────────────────── */}
      <input className="picture-file-input"
        data-ui="file-upload-input"
        ref={fileInputRef}
        type="file"
        accept="image/*"
        capture="user"
        style={{ display: 'none' }}
        onChange={handleFileChange}
      />

      {/* ── Actions ──────────────────────────────────────────── */}
      {hasPhoto && !removingBg && (
        <div data-section="controls" style={{
          display: 'flex', gap: 'var(--f-brand-space-sm)',
          padding: 'var(--f-brand-space-md) var(--f-brand-space-md) var(--f-brand-space-xl)',
          flexShrink: 0,
        }}>
          <button
            data-ui="retake-photo-btn"
            onClick={handleRetake}
            style={{
              flex: 1, height: 'var(--sp-14)', borderRadius: 'var(--f-brand-radius-rounded)',
              background: 'none', border: '1px solid var(--f-brand-color-border-default)',
              cursor: 'pointer', color: 'var(--f-brand-color-text-default)',
              font: 'var(--f-brand-type-body-medium)',
            }}
          >
            Retake photo
          </button>
          <button
            data-ui="confirm-card-btn"
            onClick={handleConfirm}
            style={{
              flex: 1, height: 'var(--sp-14)', borderRadius: 'var(--f-brand-radius-rounded)',
              background: 'var(--f-brand-color-primary)', border: 'none',
              cursor: 'pointer', color: 'var(--f-brand-color-text-light)',
              font: 'var(--f-brand-type-body-medium)',
            }}
          >
            Confirm card
          </button>
        </div>
      )}
    </div>
  )
}

// src/app/pages/picture.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  ViewChild,
  computed,
  inject,
  signal,
} from '@angular/core'
import { CommonModule } from '@angular/common'
import { Router } from '@angular/router'
import { removeBackground } from '@imgly/background-removal'
import { StoreService } from '../../store/store.service'
import { getTeamCardBackground } from '../../lib/teamCardBackground'
import { getTeam } from '../../data/teams'
import { track } from '../../lib/analytics'

const BG_REMOVAL_PUBLIC_PATH = window.location.origin + import.meta.env.BASE_URL + 'bg-removal/'

function compressDataUrl(source: HTMLVideoElement | HTMLImageElement, flipX = false): string {
  const sw = source instanceof HTMLVideoElement ? source.videoWidth : source.naturalWidth
  const sh = source instanceof HTMLVideoElement ? source.videoHeight : source.naturalHeight
  const max = 480
  const scale = Math.min(max / sw, max / sh, 1)
  const width = Math.round(sw * scale)
  const height = Math.round(sh * scale)
  const canvas = document.createElement('canvas')
  canvas.width = width
  canvas.height = height
  const ctx = canvas.getContext('2d')
  if (!ctx) {
    throw new Error('Canvas context unavailable')
  }
  if (flipX) {
    ctx.translate(width, 0)
    ctx.scale(-1, 1)
  }
  ctx.drawImage(source, 0, 0, width, height)
  return canvas.toDataURL('image/jpeg', 0.78)
}

@Component({
  selector: 'ffz-picture',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './picture.component.html',
  styleUrl: './picture.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PictureComponent {
  private readonly router = inject(Router)
  private readonly store = inject(StoreService)
  @ViewChild('cameraVideo') private cameraVideoRef?: ElementRef<HTMLVideoElement>
  @ViewChild('fileInput') private fileInputRef?: ElementRef<HTMLInputElement>

  readonly photoDataUrl = signal<string | null>(null)
  readonly cameraError = signal<string | null>(null)
  readonly bgError = signal<string | null>(null)
  readonly removingBg = signal(false)
  readonly bgProgress = signal(0)

  readonly cameraActive = signal(false)

  private stream: MediaStream | null = null
  private readonly routeTeamId = this.readTeamIdFromHistory()
  readonly teamId = computed(() => this.routeTeamId ?? this.store.state().fanCard.teamId ?? null)
  readonly selectedTeam = computed(() => (this.teamId() ? getTeam(this.teamId()!) : null))
  readonly teamCardBackground = computed(() => getTeamCardBackground(this.teamId()))
  readonly hasPhoto = computed(() => !!this.photoDataUrl() || this.removingBg())

  constructor() {
    track('picture_viewed')
  }

  onBack(): void {
    this.stopCamera()
    void this.router.navigateByUrl('/team-selection')
  }

  async onTakePhoto(): Promise<void> {
    if (this.cameraActive()) {
      await this.capturePhoto()
      return
    }
    await this.startCamera()
  }

  async onCapturePhoto(): Promise<void> {
    await this.capturePhoto()
  }

  async onFileSelected(event: Event): Promise<void> {
    const target = event.target as HTMLInputElement
    const file = target.files?.[0]
    if (!file) {
      return
    }
    const dataUrl = await this.readFileAsDataUrl(file)
    const image = await this.loadImage(dataUrl)
    const compressed = compressDataUrl(image)
    track('picture_photo_picked')
    await this.processPhoto(compressed)
  }

  async onRetake(): Promise<void> {
    this.photoDataUrl.set(null)
    this.bgError.set(null)
    const input = this.fileInputRef?.nativeElement
    if (input) {
      input.value = ''
    }
    this.stopCamera()
    track('picture_retake_tapped')
  }

  onConfirm(): void {
    this.store.updateFanCard({ photoDataUrl: this.photoDataUrl(), teamId: this.teamId() })
    track('picture_confirmed')
    void this.router.navigateByUrl('/identity')
  }

  private readTeamIdFromHistory(): string | null {
    const stateValue = history.state as { teamId?: unknown }
    return typeof stateValue.teamId === 'string' ? stateValue.teamId : null
  }

  private async startCamera(): Promise<void> {
    this.cameraError.set(null)
    if (!navigator.mediaDevices?.getUserMedia) {
      this.fileInputRef?.nativeElement.click()
      return
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: 'user', width: { ideal: 640 }, height: { ideal: 640 } },
      })
      this.stream = stream
      this.cameraActive.set(true)
      const video = this.cameraVideoRef?.nativeElement
      if (video) {
        video.srcObject = stream
        void video.play().catch(() => undefined)
      }
      track('picture_camera_started')
    } catch {
      this.cameraError.set('Camera unavailable - pick from files instead')
      this.fileInputRef?.nativeElement.click()
    }
  }

  private stopCamera(): void {
    if (!this.stream) {
      this.cameraActive.set(false)
      return
    }
    this.stream.getTracks().forEach(track => track.stop())
    this.stream = null
    this.cameraActive.set(false)
  }

  private async capturePhoto(): Promise<void> {
    const video = this.cameraVideoRef?.nativeElement
    if (!video || video.readyState < 2 || !video.videoWidth) {
      return
    }
    const rawUrl = compressDataUrl(video, true)
    this.stopCamera()
    track('picture_photo_captured')
    await this.processPhoto(rawUrl)
  }

  private async processPhoto(rawDataUrl: string): Promise<void> {
    this.removingBg.set(true)
    this.bgProgress.set(0)
    this.bgError.set(null)
    try {
      const blob = await removeBackground(rawDataUrl, {
        publicPath: BG_REMOVAL_PUBLIC_PATH,
        model: 'small',
        proxyToWorker: false,
        progress: (_key: string, current: number, total: number) => {
          if (total > 0) {
            this.bgProgress.set(Math.round((current / total) * 100))
          }
        },
      })
      const dataUrl = await this.readBlobAsDataUrl(blob)
      this.photoDataUrl.set(dataUrl)
      track('picture_bg_removed')
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error)
      this.bgError.set(message)
      this.photoDataUrl.set(rawDataUrl)
    } finally {
      this.removingBg.set(false)
    }
  }

  private readFileAsDataUrl(file: File): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader()
      reader.onload = () => resolve(String(reader.result))
      reader.onerror = reject
      reader.readAsDataURL(file)
    })
  }

  private readBlobAsDataUrl(blob: Blob): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader()
      reader.onload = () => resolve(String(reader.result))
      reader.onerror = reject
      reader.readAsDataURL(blob)
    })
  }

  private loadImage(source: string): Promise<HTMLImageElement> {
    return new Promise((resolve, reject) => {
      const image = new Image()
      image.onload = () => resolve(image)
      image.onerror = reject
      image.src = source
    })
  }
}

<div class="picture-page" data-page="picture">
  <div class="picture-header" data-section="header">
    <button
      class="picture-back-btn"
      type="button"
      data-ui="back-btn"
      aria-label="Go back"
      (click)="onBack()"
    >
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <path
          d="M15 19l-7-7 7-7"
          stroke="var(--f-brand-color-text-default)"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </button>
    <div class="picture-progress-track">
      <div class="picture-progress-fill"></div>
    </div>
  </div>

  <h2 class="picture-title">Add your picture</h2>

  @if (!hasPhoto()) {
    <div class="picture-camera-preview">
      @if (cameraActive()) {
        <div class="picture-camera-feed">
          <video #cameraVideo autoplay playsinline muted class="picture-camera-video"></video>
          <button
            type="button"
            class="picture-capture-btn"
            aria-label="Capture photo"
            (click)="onCapturePhoto()"
          >
            <span class="picture-capture-inner"></span>
          </button>
        </div>
      } @else {
        <div class="picture-placeholder-card" [style.background]="teamCardBackground()">
          <button type="button" class="picture-take-photo-btn" data-ui="take-photo-btn" (click)="onTakePhoto()">
            Take a photo
          </button>
        </div>
      }
    </div>
  } @else if (removingBg()) {
    <div class="picture-loading">
      <div class="picture-spinner"></div>
      <p class="picture-loading-text">Removing background...</p>
    </div>
  } @else {
    <div class="picture-preview">
      <img class="picture-preview-image" [src]="photoDataUrl()" alt="Your photo preview" />
    </div>
  }

  @if (cameraError()) {
    <p class="picture-error">{{ cameraError() }}</p>
  }

  @if (bgError()) {
    <p class="picture-error">Background removal failed: {{ bgError() }}</p>
  }

  <input
    #fileInput
    type="file"
    accept="image/*"
    capture="user"
    class="hidden-input"
    data-ui="file-upload-input"
    (change)="onFileSelected($event)"
  />

  @if (hasPhoto() && !removingBg()) {
    <div class="picture-actions">
      <button
        type="button"
        class="picture-btn picture-btn-secondary"
        data-ui="retake-photo-btn"
        (click)="onRetake()"
      >
        Retake photo
      </button>
      <button
        type="button"
        class="picture-btn picture-btn-primary"
        data-ui="confirm-card-btn"
        (click)="onConfirm()"
      >
        Confirm card
      </button>
    </div>
  }
</div>
