// src/pages/card/card.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, ElementRef, ViewChild, computed, inject } from '@angular/core';
import { Router } from '@angular/router';

import { FanCardComponent } from '../../components/fan-card/fan-card.component';
import { ScreenComponent } from '../../components/screen/screen.component';
import { FlowId } from '../../models/flow-id.model';
import { AnalyticsService } from '../../services/analytics.service';
import { CardExportService } from '../../services/card-export.service';
import { QAAppService } from '../../services/qaapp.service';
import { StoreService } from '../../services/store.service';

interface JourneyMilestone {
  iconSrc: string;
  label: string;
  completed: boolean;
}

interface QuizFlowCard {
  id: FlowId;
  title: string;
  subtitle: string;
  iconSrc: string;
  route: string;
  routeState: Record<string, string>;
  type: 'quiz' | 'swipe' | 'card_match' | 'ranking';
}

@Component({
  standalone: true,
  imports: [CommonModule, ScreenComponent, FanCardComponent],
  template: `
    <app-screen className="f-card-page">
      <main class="f-card-page__content f-page-enter hide-scrollbar" data-page="card">
        <section #fanCardSection class="f-card-page__fan-card" aria-label="Your fan card">
          <app-fan-card
            [fanCard]="state().fanCard"
            (onSave)="handleFanCardSave($event)"
            (share)="handleShare()"
            (saveToDevice)="handleSaveToDevice()"
          />
        </section>

        <section class="f-card-page__journey" data-section="journey-tracker" aria-label="Your journey">
          <div class="f-card-page__journey-header">
            <div>
              <p class="f-card-page__journey-label">Your journey</p>
              <h2 class="f-card-page__journey-title">{{ journeyStatusTitle() }}</h2>
            </div>
            <span class="f-card-page__journey-pill">Step {{ currentStep() }}/4</span>
          </div>

          <div class="f-card-page__journey-track">
            @for (milestone of milestones(); track milestone.label; let idx = $index; let last = $last) {
              <div class="f-card-page__journey-item">
                <div
                  class="f-card-page__journey-node"
                  [class.f-card-page__journey-node--completed]="milestone.completed"
                  [class.f-card-page__journey-node--current]="idx === currentMilestoneIndex()"
                >
                  @if (idx === currentMilestoneIndex()) {
                    <div class="animate-ping-slow f-card-page__journey-ping"></div>
                  }
                  @if (milestone.completed) {
                    <img
                      class="f-card-page__journey-icon f-card-page__journey-icon--tick"
                      src="assets/icons/Tick-black.svg"
                      alt=""
                    />
                  } @else {
                    <img
                      class="f-card-page__journey-icon"
                      [src]="milestone.iconSrc"
                      alt=""
                    />
                  }
                </div>
                <p
                  class="f-card-page__journey-step-label"
                  [class.f-card-page__journey-step-label--inactive]="!milestone.completed && idx !== currentMilestoneIndex()"
                >
                  {{ milestone.label }}
                </p>
              </div>
              @if (!last) {
                <div
                  class="f-card-page__journey-line"
                  [class.f-card-page__journey-line--completed]="isConnectorCompleted(idx)"
                  [class.f-card-page__journey-line--half]="isConnectorHalfCompleted(idx)"
                  [class.f-card-page__journey-line--inactive]="!isConnectorCompleted(idx) && !isConnectorHalfCompleted(idx)"
                ></div>
              }
            }
          </div>

          <button
            type="button"
            class="f-card-page__journey-cta"
            [class.f-card-page__journey-cta--all-complete]="allQuizzesCompleted()"
            data-ui="journey-cta"
            [disabled]="isJourneyCtaDisabled()"
            (click)="handleJourneyCta()"
          >
            {{ journeyCtaLabel() }}
          </button>
        </section>

        <section
          #quizSection
          class="f-card-page__quiz-section"
          data-section="quiz-hub"
          aria-label="Quiz hub"
        >
          <h2 class="f-card-page__quiz-heading">Earn Avios</h2>
          <p class="f-card-page__quiz-description">
            Complete quizzes to get a chance to earn Avios rewards
          </p>

          <div class="f-card-page__quiz-grid f-stagger">
            @for (flow of flowCards; track flow.id) {
              <button
                type="button"
                class="f-card-page__quiz-card"
                [class.f-card-page__quiz-card--locked]="isFlowLocked(flow)"
                [class.f-card-page__quiz-card--completed]="isFlowCompleted(flow.id)"
                [disabled]="isFlowLocked(flow)"
                (click)="handleStartFlow(flow)"
              >
                <div class="f-card-page__quiz-card-content">
                  <div class="f-card-page__quiz-ring-wrap">
                    <svg
                      class="f-card-page__quiz-ring"
                      [attr.width]="quizRingRadius * 2"
                      [attr.height]="quizRingRadius * 2"
                      aria-hidden="true"
                    >
                      <circle
                        class="f-card-page__quiz-ring-track"
                        [attr.cx]="quizRingRadius"
                        [attr.cy]="quizRingRadius"
                        [attr.r]="quizRingNormRadius"
                        [attr.stroke-width]="quizRingStroke"
                      />
                      @if (isFlowCompleted(flow.id)) {
                        <circle
                          class="f-card-page__quiz-ring-arc"
                          [attr.cx]="quizRingRadius"
                          [attr.cy]="quizRingRadius"
                          [attr.r]="quizRingNormRadius"
                          [attr.stroke-width]="quizRingStroke"
                          [attr.stroke-dasharray]="quizRingCircumference"
                          [attr.stroke-dashoffset]="0"
                        />
                      }
                    </svg>
                    <div class="f-card-page__quiz-icon-wrap">
                      @if (isFlowLocked(flow)) {
                        <img class="f-card-page__quiz-icon f-card-page__quiz-icon--locked" src="assets/icons/Lock-white.svg" alt="" />
                      } @else if (isFlowCompleted(flow.id)) {
                        <img class="f-card-page__quiz-icon" src="assets/icons/Tick-black.svg" alt="" />
                      } @else {
                        <img class="f-card-page__quiz-icon f-card-page__quiz-icon--quiz" [src]="flow.iconSrc" alt="" />
                      }
                    </div>
                  </div>

                  <div class="f-card-page__quiz-copy">
                    <h3 class="f-card-page__quiz-title">{{ flow.title }}</h3>
                    <p
                      class="f-card-page__quiz-subtitle"
                      [class.f-card-page__quiz-subtitle--default]="!isFlowLocked(flow)"
                    >
                      {{ getFlowStatusLabel(flow) }}
                    </p>
                  </div>
                </div>

                @if (!isFlowLocked(flow) && !isFlowCompleted(flow.id)) {
                  <span class="f-card-page__quiz-action">
                    <img src="assets/icons/Chevron-right-white.svg" alt="" />
                  </span>
                }
              </button>
            }
          </div>
        </section>
      </main>
    </app-screen>
  `,
  styles: [
    `
      .f-card-page {
        background: var(--c-lt-bg);
      }

      .f-card-page__content {
        display: flex;
        flex-direction: column;
        min-height: 100%;
        padding: var(--sp-4) var(--sp-6);
        gap: var(--sp-4);
      }

      .f-card-page__fan-card {
        width: 100%;
      }

      .f-card-page__journey {
        background: var(--f-brand-color-background-light);
        border-radius: var(--f-brand-radius-outer);
        box-shadow: var(--f-brand-shadow-medium);
        padding: var(--sp-4);
        display: flex;
        flex-direction: column;
        gap: var(--sp-4);
      }

      .f-card-page__journey-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: var(--sp-3);
      }

      .f-card-page__journey-label {
        margin: 0;
        font: var(--f-brand-type-caption-medium);
        letter-spacing: var(--tracking-wide);
        color: var(--f-brand-color-text-muted);
      }

      .f-card-page__journey-title {
        margin: 0;
        font: var(--f-brand-type-headline-medium);
        letter-spacing: var(--tracking-semi);
        color: var(--f-brand-color-text-default);
      }

      .f-card-page__journey-pill {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        border-radius: var(--f-brand-radius-rounded);
        padding: 10px var(--f-brand-space-md);
        font: var(--f-brand-type-caption);
        color: var(--f-brand-color-text-subtle);
        background: var(--f-brand-color-background-default);
      }

      .f-card-page__journey-track {
        display: flex;
        align-items: flex-start;
        width: 100%;
      }

      .f-card-page__journey-item {
        width: var(--sp-14);
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: var(--sp-2);
        flex-shrink: 0;
      }

      .f-card-page__journey-node {
        width: var(--sp-14);
        min-height: var(--sp-14);
        border-radius: var(--r-full);
        display: flex;
        align-items: center;
        justify-content: center;
        position: relative;
        backdrop-filter: blur(12px);
        -webkit-backdrop-filter: blur(12px);
        background: var(--c-lt-tint-faint);
        border: var(--f-brand-border-size-default) solid var(--f-brand-color-border-default);
        transition: all var(--f-brand-motion-duration-quick) var(--f-brand-motion-easing-default);
      }

      .f-card-page__journey-node--completed {
        background: var(--f-brand-color-background-success);
        border-color: var(--f-brand-color-background-success);
        box-shadow: var(--c-lt-shadow-glow);
        transform: scale(1.1);
        z-index: 20;
      }

      .f-card-page__journey-node--current {
        transform: scale(1.05);
        z-index: 20;
        background: var(--c-lt-tint);
        border-color: var(--f-brand-color-border-default);
      }

      .f-card-page__journey-ping {
        position: absolute;
        inset: 0;
        border-radius: var(--r-full);
        background: var(--f-brand-color-background-success);
        pointer-events: none;
      }

      .f-card-page__journey-icon {
        width: var(--sp-6);
        height: var(--sp-6);
        filter: invert(1);
        position: relative;
        z-index: 1;
      }

      .f-card-page__journey-node:not(.f-card-page__journey-node--current):not(.f-card-page__journey-node--completed)
        .f-card-page__journey-icon {
        opacity: 0.6;
      }

      .f-card-page__journey-icon--tick {
        filter: invert(1);
      }

      .f-card-page__journey-step-label {
        margin: 0;
        text-align: center;
        font: var(--f-brand-type-caption);
        letter-spacing: var(--tracking-semi);
        color: var(--f-brand-color-text-default);
      }

      .f-card-page__journey-step-label--inactive {
        color: var(--f-brand-color-text-subtle);
      }

      .f-card-page__journey-line {
        flex: 1;
        height: 2px;
        margin-top: calc(var(--sp-14) / 2 - 1px);
        background: var(--f-brand-color-border-default);
        transition: all var(--f-brand-motion-duration-quick) var(--f-brand-motion-easing-default);
      }

      .f-card-page__journey-line--completed {
        background: var(--f-brand-color-background-success);
      }

      .f-card-page__journey-line--half {
        background: linear-gradient(
          90deg,
          var(--f-brand-color-background-success),
          var(--f-brand-color-border-default)
        );
      }

      .f-card-page__journey-line--inactive {
        opacity: 0.4;
      }

      .f-card-page__journey-cta {
        width: 100%;
        min-height: var(--sp-12);
        border: none;
        border-radius: var(--f-brand-radius-rounded);
        background: var(--f-brand-color-background-primary);
        color: var(--f-brand-color-text-light);
        font: var(--f-brand-type-body-medium);
        cursor: pointer;
        transition: background var(--f-brand-motion-duration-instant) var(--f-brand-motion-easing-default);
      }

      .f-card-page__journey-cta--all-complete {
        background: var(--c-accent-soft);
        color: var(--c-accent);
        border: var(--f-brand-border-size-default) solid var(--c-accent-border);
      }

      .f-card-page__journey-cta:hover {
        background: var(--f-brand-color-background-primary-hover);
      }

      .f-card-page__journey-cta--all-complete:hover {
        background: var(--c-accent-soft);
      }

      .f-card-page__journey-cta:disabled {
        cursor: default;
      }

      .f-card-page__journey-cta:focus-visible {
        outline: var(--f-brand-border-size-focused) solid var(--f-brand-color-border-primary);
        outline-offset: var(--sp-1);
      }

      .f-card-page__quiz-section {
        padding-bottom: var(--sp-10);
      }

      .f-card-page__quiz-heading {
        margin: 0;
        font: var(--f-brand-type-title-2);
        letter-spacing: var(--tracking-tighter);
        color: var(--f-brand-color-text-default);
      }

      .f-card-page__quiz-description {
        margin: var(--sp-1) 0 0;
        font: var(--f-brand-type-subheading);
        color: var(--f-brand-color-text-default);
      }

      .f-card-page__quiz-grid {
        margin-top: var(--sp-4);
        display: grid;
        gap: var(--f-brand-space-md);
      }

      .f-card-page__quiz-card {
        width: 100%;
        min-height: 120px;
        border: none;
        border-radius: var(--f-brand-radius-outer);
        background: var(--f-brand-color-background-light);
        box-shadow: var(--f-brand-shadow-medium);
        padding: var(--sp-5) var(--sp-4);
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: var(--f-brand-space-md);
        text-align: left;
        cursor: pointer;
        transition: all var(--f-brand-motion-duration-quick) var(--f-brand-motion-easing-default);
      }

      .f-card-page__quiz-card:focus-visible {
        outline: var(--f-brand-border-size-focused) solid var(--f-brand-color-border-primary);
        outline-offset: var(--sp-1);
      }

      .f-card-page__quiz-card--completed {
        background: var(--f-brand-color-background-light);
      }

      .f-card-page__quiz-card--locked {
        background: var(--f-brand-color-background-light);
        opacity: 0.55;
        cursor: not-allowed;
      }

      .f-card-page__quiz-card-content {
        display: flex;
        align-items: center;
        gap: var(--f-brand-space-md);
        min-width: 0;
      }

      .f-card-page__quiz-ring-wrap {
        width: 64px;
        height: 64px;
        position: relative;
        flex-shrink: 0;
      }

      .f-card-page__quiz-ring {
        position: absolute;
        top: 0;
        left: 0;
        transform: rotate(-90deg);
      }

      .f-card-page__quiz-ring-track {
        fill: none;
        stroke: var(--f-brand-color-border-default);
      }

      .f-card-page__quiz-ring-arc {
        fill: none;
        stroke: var(--f-brand-color-flight-status-confirmed);
        stroke-linecap: round;
        transition: stroke-dashoffset var(--f-brand-motion-duration-quick) var(--f-brand-motion-easing-default);
      }

      .f-card-page__quiz-icon-wrap {
        position: absolute;
        top: 6px;
        left: 6px;
        width: 52px;
        min-height: 52px;
        border-radius: var(--r-full);
        background: linear-gradient(135deg, var(--c-lt-tint-subtle), var(--c-lt-tint-faint));
        display: flex;
        align-items: center;
        justify-content: center;
        flex-shrink: 0;
        box-shadow: var(--c-lt-shadow-sm);
      }

      .f-card-page__quiz-card--completed .f-card-page__quiz-icon-wrap {
        background: linear-gradient(135deg, var(--c-accent-soft), var(--c-accent-faint));
      }

      .f-card-page__quiz-card--locked .f-card-page__quiz-icon-wrap {
        background: var(--c-lt-tint-subtle);
        box-shadow: none;
      }

      .f-card-page__quiz-icon {
        width: var(--sp-6);
        height: var(--sp-6);
      }

      .f-card-page__quiz-icon--quiz,
      .f-card-page__quiz-icon--locked {
        filter: invert(1);
      }

      .f-card-page__quiz-icon--locked {
        opacity: 0.4;
      }

      .f-card-page__quiz-copy {
        min-width: 0;
      }

      .f-card-page__quiz-title {
        margin: 0;
        font: var(--f-brand-type-headline-medium);
        color: var(--f-brand-color-text-default);
      }

      .f-card-page__quiz-card--locked .f-card-page__quiz-title {
        color: var(--f-brand-color-text-disabled);
      }

      .f-card-page__quiz-subtitle {
        margin: var(--sp-1) 0 0;
        font: var(--f-brand-type-caption);
        color: var(--f-brand-color-text-subtle);
      }

      .f-card-page__quiz-subtitle--default {
        color: var(--f-brand-color-text-default);
      }

      .f-card-page__quiz-card--locked .f-card-page__quiz-subtitle {
        color: var(--f-brand-color-text-subtle);
      }

      .f-card-page__quiz-action {
        width: var(--sp-9);
        min-height: var(--sp-9);
        border-radius: var(--r-full);
        display: flex;
        align-items: center;
        justify-content: center;
        background: var(--c-lt-tint);
        flex-shrink: 0;
      }

      .f-card-page__quiz-action img {
        width: var(--sp-6);
        height: var(--sp-6);
        filter: invert(1);
      }

      @media (prefers-reduced-motion: reduce) {
        .f-card-page__journey-node,
        .f-card-page__journey-cta {
          transition: none;
        }
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CardComponent {
  private readonly router = inject(Router);
  private readonly store = inject(StoreService);
  private readonly analytics = inject(AnalyticsService);
  private readonly cardExportService = inject(CardExportService);
  private readonly qaappService = inject(QAAppService);

  @ViewChild('fanCardSection') private readonly fanCardSection?: ElementRef<HTMLElement>;
  @ViewChild('quizSection') private readonly quizSection?: ElementRef<HTMLElement>;
  @ViewChild(FanCardComponent) private readonly fanCardComponent?: FanCardComponent;

  readonly state = this.store.state;
  readonly quizRingRadius = 32;
  readonly quizRingStroke = 4;
  readonly quizRingNormRadius = this.quizRingRadius - this.quizRingStroke / 2;
  readonly quizRingCircumference = 2 * Math.PI * this.quizRingNormRadius;

  readonly flowCards: ReadonlyArray<QuizFlowCard> = [
    {
      id: 'the-connector',
      title: 'The Connector',
      subtitle: '5 questions · Quiz',
      iconSrc: 'assets/icons/globe-white.svg',
      route: '/quiz',
      routeState: { quizId: 'the-connector' },
      type: 'quiz',
    },
    {
      id: 'the-architect',
      title: 'The Architect',
      subtitle: '5 rounds · Card Match',
      iconSrc: 'assets/icons/stadium-white.svg',
      route: '/card-match',
      routeState: { flowId: 'the-architect' },
      type: 'card_match',
    },
    {
      id: 'the-historian',
      title: 'The Historian',
      subtitle: '10 statements · Swipe',
      iconSrc: 'assets/icons/history-white.svg',
      route: '/swipe-quiz',
      routeState: { quizId: 'the-historian' },
      type: 'swipe',
    },
    {
      id: 'the-referee',
      title: 'The Referee',
      subtitle: '5 questions · Quiz',
      iconSrc: 'assets/icons/referee-white.svg',
      route: '/quiz',
      routeState: { quizId: 'the-referee' },
      type: 'quiz',
    },
    {
      id: 'the-retrospective',
      title: 'The Retrospective',
      subtitle: '5 questions · Ranking',
      iconSrc: 'assets/icons/ranking-white.svg',
      route: '/ranking-quiz',
      routeState: { quizId: 'the-retrospective' },
      type: 'ranking',
    },
  ];

  readonly milestones = computed<JourneyMilestone[]>(() => {
    return [
      {
        iconSrc: 'assets/icons/qr-logo.svg',
        label: 'Fan card',
        completed: this.isCardComplete(),
      },
      {
        iconSrc: 'assets/icons/globe-dark.svg',
        label: 'Connector',
        completed: this.isFlowCompleted('the-connector'),
      },
      {
        iconSrc: 'assets/icons/stadium-dark.svg',
        label: 'Architect',
        completed: this.isFlowCompleted('the-architect'),
      },
      {
        iconSrc: 'assets/icons/history-dark.svg',
        label: 'Historian',
        completed: this.isFlowCompleted('the-historian'),
      },
    ];
  });

  readonly completedMilestones = computed(() =>
    this.milestones().filter(milestone => milestone.completed).length
  );

  readonly currentStep = computed(() =>
    Math.min(this.completedMilestones() + 1, this.milestones().length)
  );

  readonly currentMilestoneIndex = computed(() => {
    return this.milestones().findIndex(milestone => !milestone.completed);
  });

  readonly journeyCtaLabel = computed(() => {
    if (this.allQuizzesCompleted()) {
      return 'All quizzes completed!';
    }
    if (!this.isCardComplete()) {
      return 'Complete fan card';
    }
    return 'Start quiz';
  });

  readonly journeyStatusTitle = computed(() => {
    const done = this.completedMilestones();
    if (done === 0) {
      return 'New arrival';
    }
    if (done === 1) {
      return 'Rising fan';
    }
    if (done <= 2) {
      return 'Quiz taker';
    }
    if (done <= 3) {
      return 'Top fan';
    }
    return 'Quiz champion';
  });

  handleFanCardSave(answers: Record<string, string>): void {
    this.store.updateFanCard({
      answers,
      completedAt: new Date().toISOString(),
    });
  }

  async handleShare(): Promise<void> {
    try {
      const blob = await this.cardExportService.renderCardToBlob(this.state().fanCard);
      const file = new File([blob], 'fifa-fan-card.png', { type: 'image/png' });
      if (navigator.canShare?.({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: 'My FIFA fan card',
          text: this.buildShareText(),
        });
      } else {
        await this.qaappService.openNativeShare({
          title: 'My FIFA fan card',
          text: this.buildShareText(),
        });
      }
      this.analytics.track('card_shared');
    } catch {
      // User cancelled or share target is unavailable.
    }
  }

  async handleSaveToDevice(): Promise<void> {
    try {
      const blob = await this.cardExportService.renderCardToBlob(this.state().fanCard);
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = 'my-fan-card.png';
      document.body.appendChild(anchor);
      anchor.click();
      document.body.removeChild(anchor);
      URL.revokeObjectURL(url);
      this.analytics.track('card_saved_to_device');
    } catch {
      // Save fallback intentionally fails silently.
    }
  }

  handleJourneyCta(): void {
    if (this.isJourneyCtaDisabled()) {
      return;
    }

    if (!this.isCardComplete()) {
      this.analytics.track('complete_fan_card_journey_tapped');
      this.scrollToElement(this.fanCardSection);
      window.setTimeout(() => this.fanCardComponent?.startEditing(), 400);
      return;
    }

    this.analytics.track('card_start_quiz_tapped');
    const nextFlow = this.flowCards.find(flow => !this.isFlowCompleted(flow.id) && !this.isFlowLocked(flow));
    if (nextFlow) {
      this.handleStartFlow(nextFlow);
      return;
    }

    this.scrollToElement(this.quizSection);
  }

  handleStartFlow(flow: QuizFlowCard): void {
    if (this.isFlowLocked(flow)) {
      return;
    }
    this.analytics.track('quiz_card_tapped', { quizId: flow.id, type: flow.type });
    void this.router.navigateByUrl(flow.route, { state: flow.routeState });
  }

  isFlowLocked(flow: QuizFlowCard): boolean {
    return !this.isCardComplete() || !this.store.isFlowUnlocked(flow.id);
  }

  isFlowCompleted(flowId: FlowId): boolean {
    return this.state().completedFlows.includes(flowId);
  }

  getFlowStatusLabel(flow: QuizFlowCard): string {
    if (this.isFlowCompleted(flow.id)) {
      const result = this.state().quizResults[flow.id];
      if (result) {
        return `Completed · ${result.score}/${result.total} correct`;
      }
      return 'Completed';
    }
    if (this.isFlowLocked(flow)) {
      return this.isCardComplete()
        ? 'Complete the previous quiz to unlock'
        : 'Complete your fan card to unlock';
    }
    return flow.subtitle;
  }

  private isCardComplete(): boolean {
    return this.state().fanCard.completedAt !== null;
  }

  allQuizzesCompleted(): boolean {
    return this.state().completedFlows.length >= this.flowCards.length;
  }

  isJourneyCtaDisabled(): boolean {
    return this.allQuizzesCompleted();
  }

  isConnectorCompleted(index: number): boolean {
    const current = this.milestones()[index]?.completed ?? false;
    const next = this.milestones()[index + 1]?.completed ?? false;
    return current && next;
  }

  isConnectorHalfCompleted(index: number): boolean {
    const current = this.milestones()[index]?.completed ?? false;
    const next = this.milestones()[index + 1]?.completed ?? false;
    return current && !next;
  }

  private scrollToElement(target?: ElementRef<HTMLElement>): void {
    target?.nativeElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }

  private buildShareText(): string {
    const fanCard = this.state().fanCard;
    const lines: string[] = ['My FIFA fan card'];
    if (fanCard.teamId) {
      lines.push(`Team: ${fanCard.teamId.toUpperCase()}`);
    }
    for (const [key, value] of Object.entries(fanCard.answers)) {
      if (value) {
        lines.push(`${key}: ${value}`);
      }
    }
    return lines.join('\n');
  }
}

// src/routes/Card.tsx
import { useRef, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import Screen from '../components/Screen'
import FanCard from '../components/FanCard'
import { track } from '../lib/analytics'
import { useStore } from '../store/useStore'
import { renderCardToBlob, buildShareText } from '../lib/cardExport'
import { QUIZZES } from '../data/quizzes'
import lockIcon    from '../assets/icons/Lock-white.svg'
import chevRight   from '../assets/icons/Chevron-right-white.svg'
import tickBlack   from '../assets/icons/Tick-black.svg'
import targetIcon  from '../assets/icons/Target-white.svg'
import fireIcon    from '../assets/icons/Fire-white.svg'
import trophyIcon  from '../assets/icons/Trophy-white.svg'
import qrIcon      from '../assets/icons/qr-logo.svg'

// ─── Milestone config ─────────────────────────────────────────────────────────
const MILESTONES = [
  { iconSrc: qrIcon,     label: 'Fan card',   key: 'card'     },
  { iconSrc: targetIcon, label: '1st quiz',    key: 'quiz1'    },
  { iconSrc: fireIcon,   label: '3 quizzes',   key: 'quiz3'    },
  { iconSrc: trophyIcon, label: 'Champion',    key: 'champion' },
] as const

function statusLabel(done: number): string {
  if (done === 0) return 'New arrival'
  if (done === 1) return 'Rising fan'
  if (done === 2) return 'Quiz taker'
  if (done === 3) return 'Top fan'
  return 'Quiz champion'
}

// ─── Journey Step ─────────────────────────────────────────────────────────────
function JourneyStep({
  iconSrc,
  label,
  isCompleted = false,
  isCurrent = false,
}: {
  iconSrc: string
  label: string
  isCompleted?: boolean
  isCurrent?: boolean
}) {
  const nodeStyle: React.CSSProperties = {
    width: 56, height: 56, borderRadius: '50%',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    backdropFilter: 'blur(12px)', WebkitBackdropFilter: 'blur(12px)',
    transition: 'all 700ms ease',
    flexShrink: 0, position: 'relative',
    ...(isCompleted ? {
      background: '#ffffff', border: '1px solid #ffffff',
      boxShadow: '0 0 25px rgba(255,255,255,0.4)',
      transform: 'scale(1.1)', zIndex: 20,
    } : isCurrent ? {
      background: 'rgba(255,255,255,0.15)', border: '1px solid rgba(255,255,255,0.4)',
      transform: 'scale(1.05)', zIndex: 20,
      boxShadow: '0 10px 25px rgba(0,0,0,0.3)',
    } : {
      background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.1)',
      zIndex: 10,
    }),
  }

  return (
    <li style={{
      position: 'relative', zIndex: 10,
      display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12,
      width: 56, flexShrink: 0,
    }}>
      <div style={nodeStyle}>
        {isCurrent && (
          <div
            className="animate-ping-slow"
            style={{
              position: 'absolute', inset: 0, borderRadius: '50%',
              background: 'rgba(255,255,255,0.3)', pointerEvents: 'none',
            }}
          />
        )}
        {isCompleted ? (
          <img src={tickBlack} width={20} height={20} alt="" style={{ position: 'relative', zIndex: 10 }} />
        ) : (
          <img src={iconSrc} width={20} height={20} alt="" style={{ opacity: isCurrent ? 1 : 0.3 }} />
        )}
      </div>
      <span style={{
        fontFamily: 'var(--font-body)', fontWeight: 'var(--weight-reg)',
        fontSize: 12, letterSpacing: '-0.02em', textAlign: 'center',
        whiteSpace: 'nowrap', transition: 'color 500ms ease',
        color: isCompleted || isCurrent ? '#ffffff' : 'rgba(255,255,255,0.3)',
      }}>
        {label}
      </span>
    </li>
  )
}

// ─── Journey Card ─────────────────────────────────────────────────────────────
function JourneyCard({
  completedAt,
  quizCount,
  onStartQuiz,
}: {
  completedAt: string | null
  quizCount: number
  onStartQuiz: () => void
}) {
  const achieved = [
    completedAt !== null,
    quizCount >= 1,
    quizCount >= 3,
    quizCount >= 5,
  ]
  const doneCount = achieved.filter(Boolean).length
  const status = statusLabel(doneCount)

  // Find first incomplete milestone for "current" indicator
  const currentIdx = achieved.findIndex(v => !v)

  return (
    <section
      aria-label="Your Journey Progress"
      style={{
        width: '100%',
        background: 'rgba(255,255,255,0.08)',
        borderRadius: 20,
        padding: 16,
        border: '1px solid rgba(255,255,255,0.15)',
        marginBottom: 16,
        boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.06)',
        overflow: 'hidden',
      }}
    >
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
        <div>
          <h2 style={{
            fontFamily: 'var(--font-body)', fontWeight: 'var(--weight-med)',
            fontSize: 12, letterSpacing: '0.05em',
            color: 'rgba(255,255,255,0.7)', marginBottom: 4,
          }}>
            Your journey
          </h2>
          <p style={{
            fontFamily: 'var(--font-body)', fontWeight: 'var(--weight-med)',
            fontSize: 18, letterSpacing: '-0.02em', color: '#ffffff',
          }}>
            {status}
          </p>
        </div>
        <div style={{
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          padding: '10px 16px',
          background: 'rgba(255,255,255,0.2)',
          borderRadius: 9999,
          border: '1px solid rgba(255,255,255,0.2)',
        }}>
          <span style={{
            fontFamily: 'var(--font-body)', fontWeight: 'var(--weight-reg)',
            fontSize: 12, color: '#ffffff', lineHeight: 1,
          }}>
            Step {Math.min(doneCount + 1, 4)}/4
          </span>
        </div>
      </div>

      {/* Steps track */}
      <nav aria-label="Journey Steps">
        <ol style={{ display: 'flex', alignItems: 'flex-start', width: '100%', position: 'relative', listStyle: 'none' }}>
          {MILESTONES.map((m, i) => {
            const done = achieved[i]
            const isCurrent = currentIdx === i
            const isLast = i === MILESTONES.length - 1
            return (
              <div key={m.key} style={{ display: 'contents' }}>
                <JourneyStep
                  iconSrc={m.iconSrc}
                  label={m.label}
                  isCompleted={done}
                  isCurrent={isCurrent}
                />
                {!isLast && (
                  <div style={{
                    flex: 1, height: 2, marginTop: 27,
                    background: done
                      ? 'linear-gradient(90deg, #ffffff, rgba(255,255,255,0.2))'
                      : 'rgba(255,255,255,0.1)',
                  }} />
                )}
              </div>
            )
          })}
        </ol>
      </nav>

      {/* Start Quiz CTA */}
      <button
        onClick={onStartQuiz}
        style={{
          width: '100%', height: 48,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          background: '#ffffff', color: '#8E2157',
          fontFamily: 'var(--font-body)', fontWeight: 'var(--weight-bold)',
          fontSize: 15, borderRadius: 9999, border: 'none',
          marginTop: 28, cursor: 'pointer',
          boxShadow: '0 10px 30px rgba(255,255,255,0.12)',
          transition: 'all 150ms ease',
          WebkitTapHighlightColor: 'transparent',
        }}
      >
        Start quiz
      </button>
    </section>
  )
}

// ─── Circular progress ring ───────────────────────────────────────────────────
function ProgressRing({
  radius,
  stroke,
  progress,
  color,
}: {
  radius: number
  stroke: number
  progress: number // 0–1
  color: string
}) {
  const norm = radius - stroke / 2
  const circ = 2 * Math.PI * norm
  const offset = circ * (1 - progress)
  return (
    <svg
      width={radius * 2}
      height={radius * 2}
      style={{ position: 'absolute', top: 0, left: 0, transform: 'rotate(-90deg)' }}
    >
      {/* background track */}
      <circle
        cx={radius} cy={radius} r={norm}
        fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth={stroke}
      />
      {/* progress arc */}
      {progress > 0 && (
        <circle
          cx={radius} cy={radius} r={norm}
          fill="none" stroke={color} strokeWidth={stroke}
          strokeDasharray={circ} strokeDashoffset={offset}
          strokeLinecap="round"
          style={{ transition: 'stroke-dashoffset 600ms ease' }}
        />
      )}
    </svg>
  )
}

// ─── Quiz card ────────────────────────────────────────────────────────────────
type QuizCardState = 'active' | 'done' | 'locked'

const RING_RADIUS = 40
const RING_STROKE = 3.5

function QuizCard({
  quiz,
  cardState,
  progress,
  onStart,
}: {
  quiz: (typeof QUIZZES)[number]
  cardState: QuizCardState
  progress: number
  onStart: () => void
}) {
  const locked = cardState === 'locked'
  const done   = cardState === 'done'

  return (
    <button
      onClick={locked ? undefined : onStart}
      disabled={locked}
      style={{
        width: '100%',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '18px 14px', borderRadius: 22,
        minHeight: 120,
        border: `1px solid ${locked ? 'rgba(255,255,255,0.06)' : done ? 'rgba(0,212,170,0.25)' : 'rgba(255,255,255,0.12)'}`,
        background: locked ? 'rgba(255,255,255,0.02)' : done ? 'rgba(0,212,170,0.06)' : 'rgba(255,255,255,0.05)',
        opacity: locked ? 0.55 : 1,
        cursor: locked ? 'not-allowed' : 'pointer',
        textAlign: 'left', fontFamily: 'inherit', color: 'var(--c-text-1)',
        transition: 'all 400ms ease',
        WebkitTapHighlightColor: 'transparent',
      }}
    >
      <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
        {/* Circular thumbnail with progress ring */}
        <div style={{
          width: RING_RADIUS * 2, height: RING_RADIUS * 2,
          position: 'relative', flexShrink: 0,
        }}>
          <ProgressRing
            radius={RING_RADIUS}
            stroke={RING_STROKE}
            progress={done ? 1 : 0}
            color={done ? 'var(--c-accent)' : 'rgba(255,255,255,0.3)'}
          />
          {/* Inner circle */}
          <div style={{
            position: 'absolute',
            top: RING_STROKE + 2, left: RING_STROKE + 2,
            width: (RING_RADIUS - RING_STROKE - 2) * 2,
            height: (RING_RADIUS - RING_STROKE - 2) * 2,
            borderRadius: '50%',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            background: locked
              ? 'rgba(255,255,255,0.04)'
              : done
              ? 'linear-gradient(135deg, rgba(0,212,170,0.15), rgba(0,212,170,0.05))'
              : 'linear-gradient(135deg, rgba(255,255,255,0.08), rgba(255,255,255,0.03))',
            boxShadow: locked ? 'none' : '0 6px 20px rgba(0,0,0,0.25)',
          }}>
            {locked ? (
              <img src={lockIcon} width={20} height={20} alt="" style={{ opacity: 0.4 }} />
            ) : done ? (
              <img src={tickBlack} width={22} height={22} alt="" style={{ filter: 'invert(1)' }} />
            ) : (
              <span style={{ fontSize: 30 }}>{quiz.emoji}</span>
            )}
          </div>
        </div>

        {/* Text */}
        <div>
          <h3 style={{
            fontFamily: 'var(--font-body)', fontWeight: 'var(--weight-med)',
            fontSize: 'var(--text-lg)',
            color: locked ? 'rgba(255,255,255,0.5)' : '#ffffff',
          }}>
            {quiz.title}
          </h3>
          <p style={{ fontSize: 13, color: 'rgba(255,255,255,0.5)', marginTop: 6 }}>
            {done ? (
              <span style={{ color: 'var(--c-accent)', fontWeight: 'var(--weight-med)' }}>
                Completed · {Math.round(progress * quiz.questions.length)}/{quiz.questions.length} correct
              </span>
            ) : locked ? (
              'Complete previous quiz to unlock'
            ) : (
              <span style={{ color: 'var(--c-accent)', fontWeight: 'var(--weight-med)' }}>
                {quiz.questions.length} questions · {quiz.questions.length * 15}s
              </span>
            )}
          </p>
        </div>
      </div>

      {!locked && !done && (
        <div style={{
          width: 36, height: 36, borderRadius: '50%',
          background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          marginRight: 4,
        }}>
          <img src={chevRight} width={16} height={16} alt="" style={{ opacity: 0.5 }} />
        </div>
      )}
    </button>
  )
}

// ─── Main Card route ──────────────────────────────────────────────────────────
export default function Card() {
  const navigate = useNavigate()
  const { state, updateFanCard } = useStore()
  const quizRef = useRef<HTMLDivElement>(null)

  function handleSave(answers: Record<string, string>) {
    updateFanCard({ answers, completedAt: new Date().toISOString() })
  }

  const handleShare = useCallback(async () => {
    try {
      const blob = await renderCardToBlob(state.fanCard)
      const file = new File([blob], 'fan-card.png', { type: 'image/png' })
      if (navigator.canShare?.({ files: [file] })) {
        await navigator.share({ files: [file], title: 'My FIFA Fan Card' })
      } else {
        await (window as any).QAApp.openNativeShare({
          title: 'My FIFA Fan Card',
          text: buildShareText(state.fanCard),
        })
      }
      track('card_shared')
    } catch {
      // user cancelled
    }
  }, [state.fanCard])

  const handleSaveToDevice = useCallback(async () => {
    try {
      const blob = await renderCardToBlob(state.fanCard)
      const url  = URL.createObjectURL(blob)
      const a    = document.createElement('a')
      a.href     = url
      a.download = 'my-fan-card.png'
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
      track('card_saved_to_device')
    } catch {
      // silently fail
    }
  }, [state.fanCard])

  function getCardState(i: number): QuizCardState {
    const quizId = QUIZZES[i].id
    if (state.quizResults[quizId]) return 'done'
    if (i === 0) return 'active'
    const prevId = QUIZZES[i - 1].id
    return state.quizResults[prevId] ? 'active' : 'locked'
  }

  function getProgress(i: number): number {
    const result = state.quizResults[QUIZZES[i].id]
    if (!result) return 0
    return result.score / result.total
  }

  function handleStartQuiz(quizId: string) {
    track('quiz_card_tapped', { quizId })
    navigate('/quiz', { state: { quizId } })
  }

  return (
    <Screen>
      {/* ── Background blobs ─────────────────────────────────── */}
      <div style={{ position: 'fixed', inset: 0, overflow: 'hidden', pointerEvents: 'none', zIndex: 0 }} aria-hidden="true">
        <div
          className="animate-blob-slow"
          style={{ position: 'absolute', top: '5%', left: '-10%', width: 500, height: 500, background: 'rgba(142,33,87,0.3)', borderRadius: '50%', filter: 'blur(120px)' }}
        />
        <div
          className="animate-blob-reverse"
          style={{ position: 'absolute', bottom: '5%', right: '-10%', width: 600, height: 600, background: 'rgba(142,33,87,0.4)', borderRadius: '50%', filter: 'blur(140px)' }}
        />
        <div
          className="animate-blob-float"
          style={{ position: 'absolute', top: '45%', left: '15%', width: 350, height: 350, background: 'rgba(142,33,87,0.2)', borderRadius: '50%', filter: 'blur(100px)' }}
        />
      </div>

      {/* ── Glass container ──────────────────────────────────── */}
      <div style={{
        position: 'relative', zIndex: 10,
        width: '100%', minHeight: '100%',
        background: 'transparent',
        display: 'flex', flexDirection: 'column',
      }}>
        {/* Noise texture overlay */}
        <div
          aria-hidden="true"
          style={{
            position: 'absolute', inset: 0, opacity: 0.02, pointerEvents: 'none',
            backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`,
          }}
        />

        {/* ── Content ────────────────────────────────────────── */}
        <div
          className="page-in hide-scrollbar"
          style={{
            flex: 1, position: 'relative', zIndex: 20,
            padding: '16px 24px',
            overflowY: 'auto', WebkitOverflowScrolling: 'touch',
          }}
        >

          {/* ── Fan Card ──────────────────────────────────────── */}
          <section aria-label="Your Fan Card" style={{ width: '100%', marginBottom: 16 }}>
            <FanCard
              fanCard={state.fanCard}
              onSave={handleSave}
              onShare={handleShare}
              onSaveToDevice={handleSaveToDevice}
            />
          </section>

          {/* ── Journey ───────────────────────────────────────── */}
          <JourneyCard
            completedAt={state.fanCard.completedAt}
            quizCount={Object.keys(state.quizResults).length}
            onStartQuiz={() => {
              track('card_start_quiz_tapped')
              quizRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })
            }}
          />

          {/* ── Quizzes ───────────────────────────────────────── */}
          <section ref={quizRef} style={{ paddingBottom: 48 }}>
            <div style={{ marginBottom: 16 }}>
              <h2 style={{
                fontFamily: 'var(--font-display)', fontWeight: 'var(--weight-thin)',
                fontSize: 28, letterSpacing: '-0.04em', color: '#ffffff',
              }}>
                Earn Avios
              </h2>
              <p style={{
                fontFamily: 'var(--font-body)', fontWeight: 'var(--weight-reg)',
                color: 'rgba(255,255,255,0.5)', fontSize: 14, marginTop: 4,
              }}>
                Complete quizzes to climb the leaderboard
              </p>
            </div>

            <div className="stagger" style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              {QUIZZES.map((quiz, i) => (
                <QuizCard
                  key={quiz.id}
                  quiz={quiz}
                  cardState={getCardState(i)}
                  progress={getProgress(i)}
                  onStart={() => handleStartQuiz(quiz.id)}
                />
              ))}
            </div>
          </section>
        </div>
      </div>
    </Screen>
  )
}
