// angular-migration/src/app/pages/leaderboard/leaderboard.component.ts
import { ChangeDetectionStrategy, Component, OnInit, computed, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { LEADERBOARD_REFRESH_MS, LeaderboardService } from '../../services/leaderboard.service';
import { AnalyticsService } from '../../services/analytics.service';
import { AppStoreService } from '../../services/app-store.service';
import { getTeam } from '../../data/teams';

function pad2(value: number): string {
  return String(value).padStart(2, '0');
}

function formatRefresh(date: Date): string {
  return `${pad2(date.getHours())}:${pad2(date.getMinutes())}:${pad2(date.getSeconds())}`;
}

@Component({
  selector: 'app-leaderboard',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './leaderboard.component.html',
  styleUrl: './leaderboard.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LeaderboardComponent implements OnInit {
  private readonly router = inject(Router);
  private readonly analytics = inject(AnalyticsService);
  private readonly leaderboard = inject(LeaderboardService);
  private readonly store = inject(AppStoreService);

  readonly entries = this.leaderboard.entries;
  readonly myRank = this.leaderboard.myRank;
  readonly lastRefresh = this.leaderboard.lastRefresh;
  readonly refreshMinutes = LEADERBOARD_REFRESH_MS / 60_000;

  readonly homeRoute = computed(() => (this.store.state().fanCard.teamId ? '/identity' : '/'));

  readonly subtitle = computed(
    () =>
      `Cumulative score · Updated ${formatRefresh(this.lastRefresh())} · auto-refreshes every ${this.refreshMinutes} min`
  );

  readonly rows = computed(() => {
    return this.entries().map((entry) => ({
      ...entry,
      teamFlag: getTeam(entry.teamId)?.flag ?? '🏳️',
      scoreLabel: `${entry.pts} pts`,
      durationLabel: `${entry.durationMins} min`,
    }));
  });

  ngOnInit(): void {
    this.store.markLeaderboardVisited();
    this.analytics.track('leaderboard_viewed', {
      count: this.entries().length,
      myRank: this.myRank(),
    });
  }

  onBack(): void {
    this.analytics.track('leaderboard_back_tapped');
    void this.router.navigateByUrl('/');
  }

  onRefresh(): void {
    this.analytics.track('leaderboard_refresh_tapped');
    this.leaderboard.refresh();
  }

  onReturnHome(): void {
    this.analytics.track('leaderboard_home_tapped');
    void this.router.navigateByUrl(this.homeRoute());
  }

  isTopFive(): boolean {
    const rank = this.myRank();
    return rank !== null && rank <= 5;
  }

}

<div class="leaderboard-page" data-page="leaderboard">
  <div class="leaderboard-content">
    <div class="leaderboard-header" data-section="header">
      <button
        class="leaderboard-icon-btn"
        data-ui="back-btn"
        type="button"
        aria-label="Go back"
        (click)="onBack()"
      >
        <img src="assets/icons/Chevron-left-white.svg" width="24" height="24" alt="" />
      </button>

      <h2 class="leaderboard-title">Leaderboard</h2>

      <button
        class="leaderboard-icon-btn"
        data-ui="refresh-btn"
        type="button"
        aria-label="Refresh leaderboard"
        (click)="onRefresh()"
      >
        <img src="assets/icons/flip-white.svg" width="24" height="24" alt="" />
      </button>
    </div>

    <p class="leaderboard-subtitle" data-section="subtitle">
      {{ subtitle() }}
    </p>

    @if (myRank() !== null) {
      <div class="leaderboard-your-rank" data-section="your-rank">
        <span class="leaderboard-your-rank-label">Your rank: </span>
        <span class="leaderboard-your-rank-value">#{{ myRank() }}</span>
        @if (isTopFive()) {
          <span class="leaderboard-top-five-badge">
            <img src="assets/icons/Trophy-white.svg" width="24" height="24" alt="" />
            Top 5 — Avios eligible
          </span>
        }
      </div>
    }

    <div class="leaderboard-rank-list" data-section="rank-list">
      @if (entries().length === 0) {
        <div class="leaderboard-empty">
          <img src="assets/icons/Trophy-white.svg" width="32" height="32" alt="" />
          <p>No players yet — complete a quiz to appear on the leaderboard</p>
        </div>
      }

      @for (row of rows(); track row.rank) {
        <div class="leaderboard-rank-row" [class.is-me]="row.isMe" data-section="rank-row">
          <div class="leaderboard-rank-position">
            @if (row.rank === 1) {
              <img src="assets/icons/Trophy-white.svg" width="24" height="24" alt="1" />
            } @else {
              {{ row.rank }}
            }
          </div>

          <div class="leaderboard-rank-player">
            <span class="leaderboard-rank-team-badge">{{ row.teamFlag }}</span>
            <span class="leaderboard-rank-name">{{ row.name }}</span>
            @if (row.isMe) {
              <span class="leaderboard-rank-you">you</span>
            }
          </div>

          <div class="leaderboard-rank-metric">
            <span class="leaderboard-rank-metric-label">Score</span>
            <span class="leaderboard-rank-metric-value">{{ row.scoreLabel }}</span>
          </div>

          <div class="leaderboard-rank-metric">
            <span class="leaderboard-rank-metric-label">Duration</span>
            <span class="leaderboard-rank-metric-value">{{ row.durationLabel }}</span>
          </div>
        </div>
      }
    </div>

    <p class="leaderboard-disclaimer">
      Top 5 fans win Avios. Rankings are provisional until end-of-event.
    </p>
  </div>

  <div class="leaderboard-sticky-cta">
    <button
      type="button"
      class="leaderboard-home-btn"
      data-ui="return-home-btn"
      (click)="onReturnHome()"
    >
      Return home
    </button>
  </div>
</div>

// src/routes/Leaderboard.tsx
import { useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import Screen from '../components/Screen'
import { track } from '../lib/analytics'
import { useLeaderboard, LEADERBOARD_REFRESH_MS } from '../lib/leaderboard'
import { useStore } from '../store/useStore'
import chevLeft   from '../assets/icons/Chevron-left-white.svg'
import flipIcon   from '../assets/icons/flip-white.svg'
import trophyIcon from '../assets/icons/Trophy-white.svg'

function pad2(n: number) { return String(n).padStart(2, '0') }
function formatRefresh(d: Date) { return `${pad2(d.getHours())}:${pad2(d.getMinutes())}:${pad2(d.getSeconds())}` }

export default function Leaderboard() {
  const navigate = useNavigate()
  const { state, markLeaderboardVisited } = useStore()
  const { entries, myRank, lastRefresh, refresh } = useLeaderboard()
  const homeRoute = state.fanCard.teamId ? '/card' : '/'

  useEffect(() => {
    markLeaderboardVisited()
  }, [markLeaderboardVisited])

  return (
    <Screen>
      <div data-page="leaderboard" className="f-page-enter scroll-y" style={{ display: 'flex', flexDirection: 'column', padding: 'var(--f-brand-space-lg) var(--f-brand-space-md) 100px', width: '100%', maxWidth: 420, margin: '0 auto' }}>

        {/* Header */}
        <div data-section="header" className="leaderboard-header" style={{ display: 'flex', alignItems: 'center', marginBottom: 'var(--f-brand-space-xs)' }}>
          <button data-ui="back-btn" onClick={() => navigate(-1)} className="f-button f-button--ghost leaderboard-back-btn"><img className="leaderboard-back-icon" src={chevLeft} width={24} height={24} alt="Back" /></button>
          <div className="leaderboard-title-wrapper" style={{ flex: 1, textAlign: 'center' }}>
            <h2 className="leaderboard-title" style={{
              font: 'var(--f-brand-type-headline)',
              fontWeight: 'var(--weight-light)',
              letterSpacing: 'var(--tracking-tight)',
              color: 'var(--f-brand-color-text-default)',
            }}>
              Leaderboard
            </h2>
          </div>
          <button className="f-button f-button--ghost leaderboard-refresh-btn"
            data-ui="refresh-btn"
            onClick={() => { track('leaderboard_refresh_tapped'); refresh() }}
            aria-label="Refresh leaderboard"
          ><img className="leaderboard-refresh-icon" src={flipIcon} width={24} height={24} alt="Refresh" /></button>
        </div>

        {/* Subtitle */}
        <div data-section="subtitle" className="leaderboard-subtitle" style={{ font: 'var(--f-brand-type-caption)', fontSize: 'var(--text-xs)', color: 'var(--f-brand-color-text-muted)', textAlign: 'center', marginBottom: 'var(--f-brand-space-md)', lineHeight: 'var(--leading-normal)', letterSpacing: 'var(--tracking-wide)' }}>
          Cumulative score · Updated {formatRefresh(lastRefresh)} · auto-refreshes every {LEADERBOARD_REFRESH_MS / 60_000} min
        </div>

        {/* Your rank */}
        {myRank !== null && (
          <div data-section="your-rank" className="leaderboard-your-rank" style={{
            textAlign: 'center', marginBottom: 'var(--f-brand-space-md)',
            padding: 'var(--f-brand-space-sm) var(--f-brand-space-md)',
            borderRadius: 'var(--f-brand-radius-small)',
            background: 'rgba(200,16,46,0.07)',
            border: '1px solid var(--f-brand-color-border-primary)',
            backdropFilter: 'blur(16px)',
            WebkitBackdropFilter: 'blur(16px)',
          }}>
            <span className="leaderboard-your-rank-label" style={{ font: 'var(--f-brand-type-caption)', fontSize: 'var(--text-sm)', color: 'var(--f-brand-color-text-subtle)' }}>Your rank: </span>
            <span className="leaderboard-your-rank-value" style={{ font: 'var(--f-brand-type-body-medium)', fontSize: 'var(--text-md)', color: 'var(--f-brand-color-accent)' }}>#{myRank}</span>
            {myRank <= 5 && (
              <span className="leaderboard-your-rank-badge" style={{ font: 'var(--f-brand-type-caption)', fontSize: 'var(--text-sm)', color: 'var(--f-brand-color-accent)', marginLeft: 'var(--sp-2)', display: 'inline-flex', alignItems: 'center', gap: 'var(--sp-1)' }}>
                <img className="leaderboard-your-rank-trophy" src={trophyIcon} width={24} height={24} alt="" /> Top 5 — Avios eligible!
              </span>
            )}
          </div>
        )}

        {/* Rows */}
        <div data-section="rank-list" className="f-stagger" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--f-brand-space-xs)' }}>
          {entries.length === 0 && (
            <div className="leaderboard-empty" style={{
              textAlign: 'center',
              padding: 'var(--f-brand-space-2xl) var(--f-brand-space-md)',
              color: 'var(--f-brand-color-text-muted)',
              fontSize: 'var(--text-md)',
              lineHeight: 'var(--leading-body)',
            }}>
              <img className="leaderboard-empty-icon" src={trophyIcon} width={32} height={32} alt="" style={{ opacity: 0.4, marginBottom: 'var(--f-brand-space-sm)' }} />
              <p className="leaderboard-empty-text">No players yet — complete a quiz to appear on the leaderboard</p>
            </div>
          )}
          {entries.map(row => (
            <div className="leaderboard-rank-row"
              data-section="rank-row"
              key={row.rank}
              style={{
                display: 'flex', alignItems: 'center',
                padding: 'var(--f-brand-space-md) var(--f-brand-space-md)',
                borderRadius: 'var(--f-brand-radius-small)',
                background: row.isMe ? 'rgba(200,16,46,0.07)' : 'rgba(255,255,255,0.10)',
                border: `1px solid ${row.isMe ? 'var(--f-brand-color-border-primary)' : 'var(--f-brand-color-border-default)'}`,
                backdropFilter: 'blur(16px)',
                WebkitBackdropFilter: 'blur(16px)',
                boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.14)',
                transition: 'background var(--f-brand-motion-duration-instant) var(--f-brand-motion-easing-exit)',
              }}
            >
              <div className="leaderboard-rank-number" style={{ width: 28, font: 'var(--f-brand-type-caption-medium)', fontSize: 'var(--text-sm)', color: row.rank <= 3 ? 'var(--f-brand-color-accent)' : 'var(--f-brand-color-text-muted)', flexShrink: 0, lineHeight: 'var(--leading-none)', display: 'flex', alignItems: 'center' }}>
                {row.rank === 1 ? <img className="leaderboard-rank-trophy" src={trophyIcon} width={24} height={24} alt="1" /> : row.rank}
              </div>
              <div className="leaderboard-rank-name" style={{ flex: 1, font: 'var(--f-brand-type-body)', fontSize: 'var(--text-md)', color: 'var(--f-brand-color-text-default)', fontWeight: row.isMe ? 'var(--weight-med)' : 'var(--weight-reg)' }}>
                {row.name}
                {row.isMe && <span className="leaderboard-rank-you" style={{ font: 'var(--f-brand-type-caption)', fontSize: 'var(--text-xs)', color: 'var(--f-brand-color-accent)', marginLeft: 'var(--sp-2)', letterSpacing: 'var(--tracking-wide)' }}>you</span>}
              </div>
              {[
                { label: 'Score',    value: `${row.pts} pts` },
                { label: 'Duration', value: `${row.durationMins} min` },
              ].map(col => (
                <div className="leaderboard-rank-col" key={col.label} style={{ textAlign: 'right', marginLeft: 'var(--f-brand-space-sm)', minWidth: 54 }}>
                  <div className="leaderboard-rank-col-label" style={{ font: 'var(--f-brand-type-caption)', fontSize: 'var(--text-2xs)', color: 'var(--f-brand-color-text-muted)', letterSpacing: 'var(--tracking-wider)', textTransform: 'uppercase', marginBottom: 2 }}>{col.label}</div>
                  <div className="leaderboard-rank-col-value" style={{ font: 'var(--f-brand-type-caption-medium)', fontSize: 'var(--text-sm)', color: 'var(--f-brand-color-text-default)' }}>{col.value}</div>
                </div>
              ))}
            </div>
          ))}
        </div>

        {/* Disclaimer */}
        <p className="leaderboard-disclaimer" style={{ marginTop: 'var(--f-brand-space-lg)', font: 'var(--f-brand-type-caption)', fontSize: 'var(--text-xs)', color: 'var(--f-brand-color-text-muted)', textAlign: 'center', lineHeight: 'var(--leading-normal)', letterSpacing: 'var(--tracking-wide)' }}>
          Top 5 fans win Avios. Rankings are provisional until end-of-event.
        </p>
      </div>

      {/* Sticky CTA */}
      <div className="leaderboard-sticky-cta" style={{ position: 'fixed', bottom: 0, left: 0, right: 0, padding: 'var(--f-brand-space-md) var(--f-brand-space-lg) var(--f-brand-space-xl)', background: 'linear-gradient(transparent, var(--f-brand-color-background-dark) 40%)' }}>
        <button className="f-button"
          data-ui="return-home-btn"
          onClick={() => { track('leaderboard_home_tapped'); navigate(homeRoute) }}
          style={{ width: '100%', maxWidth: 420, display: 'block', margin: '0 auto' }}
        >
          Return home
        </button>
      </div>
    </Screen>
  )
}
