// src/app/pages/team-selection.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  HostListener,
  ViewChild,
  inject,
} from '@angular/core'
import { CommonModule } from '@angular/common'
import { Router } from '@angular/router'
import { track } from '../../lib/analytics'
import { WORLD_CUP_TEAMS, type WorldCupTeam } from '../../data/teams'

@Component({
  selector: 'ffz-team-selection-page',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './team-selection.component.html',
  styleUrl: './team-selection.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TeamSelectionComponent {
  private readonly router = inject(Router)

  @ViewChild('dropdownRoot', { static: true }) dropdownRoot!: ElementRef<HTMLDivElement>

  selectedId: string | null = null
  open = false
  readonly teams = WORLD_CUP_TEAMS

  ngOnInit(): void {
    track('team_selection_viewed')
  }

  get selectedTeam(): WorldCupTeam | null {
    if (!this.selectedId) {
      return null
    }
    return this.teams.find(team => team.id === this.selectedId) ?? null
  }

  @HostListener('document:mousedown', ['$event'])
  closeDropdownOnOutsideClick(event: MouseEvent): void {
    const target = event.target as Node | null
    if (!target) {
      return
    }
    if (!this.dropdownRoot.nativeElement.contains(target)) {
      this.open = false
    }
  }

  onBack(): void {
    track('team_selection_back_tapped')
    void this.router.navigateByUrl('/')
  }

  toggleDropdown(): void {
    this.open = !this.open
  }

  onTeamSelect(teamId: string): void {
    this.selectedId = teamId
    this.open = false
    track('team_selection_team_selected', { teamId })
  }

  onContinue(): void {
    if (!this.selectedId) {
      return
    }
    void this.router.navigate(['/picture'], { state: { teamId: this.selectedId } })
  }
}

<div class="team-selection-page" data-page="team-selection">
  <div class="team-selection-header" data-section="header">
    <button
      class="team-selection-back-btn"
      data-ui="back-btn"
      type="button"
      aria-label="Go back"
      (click)="onBack()"
    >
      <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true">
        <path
          d="M15 19l-7-7 7-7"
          stroke="var(--f-brand-color-text-default)"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </button>
    <div class="team-selection-progress-track">
      <div class="team-selection-progress-fill"></div>
    </div>
  </div>

  <h2 class="team-selection-title" data-section="title">Select your team</h2>

  <div class="team-selection-dropdown" data-section="team-dropdown" #dropdownRoot>
    <button
      class="team-selection-dropdown-btn"
      data-ui="team-dropdown-btn"
      type="button"
      [attr.aria-expanded]="open"
      aria-haspopup="listbox"
      (click)="toggleDropdown()"
      [class.has-value]="selectedTeam"
    >
      <span>{{ selectedTeam?.name ?? 'Select a team' }}</span>
      <svg
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        aria-hidden="true"
        [style.transform]="open ? 'rotate(180deg)' : 'rotate(0deg)'"
      >
        <path
          d="M6 9l6 6 6-6"
          stroke="var(--f-brand-color-text-subtle)"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
    </button>

    @if (open) {
      <ul class="team-selection-dropdown-list" role="listbox">
        @for (team of teams; track team.id) {
          <li
            class="team-selection-dropdown-item"
            role="option"
            [attr.aria-selected]="team.id === selectedId"
            (click)="onTeamSelect(team.id)"
          >
            {{ team.name }}
          </li>
        }
      </ul>
    }
  </div>

  <div class="team-selection-spacer"></div>

  <p class="team-selection-login-prompt">
    Already have a card? <span class="team-selection-login-link">Log in</span>
  </p>

  <button
    class="team-selection-continue-btn"
    data-section="confirm-cta"
    data-ui="continue-btn"
    type="button"
    [disabled]="!selectedId"
    (click)="onContinue()"
  >
    Add your photo
  </button>
</div>

// src/routes/TeamSelection.tsx
import { useState, useRef, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { track } from '../lib/analytics'
import { WORLD_CUP_TEAMS } from '../data/teams'

/* ── Progress bar (reused from Picture flow) ──────────────────────────────── */
function ProgressBar({ progress }: { progress: number }) {
  return (
    <div
      className="team-selection-progress-track"
      style={{
        flex: 1,
        height: 8,
        borderRadius: 'var(--f-brand-radius-rounded)',
        background: 'var(--f-brand-color-border-default)',
        overflow: 'hidden',
      }}
    >
      <div
        className="team-selection-progress-fill"
        style={{
          width: `${progress}%`,
          height: '100%',
          borderRadius: 'var(--f-brand-radius-rounded)',
          background: 'linear-gradient(-90deg, var(--f-brand-color-border-success) 61.5%, var(--f-brand-color-background-success) 100%)',
          boxShadow: '1px 0px 6px var(--f-brand-shadow-large)',
          transition: `width var(--f-brand-motion-duration-quick) var(--f-brand-motion-easing-exit)`,
        }}
      />
    </div>
  )
}

/* ── TeamSelection ────────────────────────────────────────────────────────── */
export default function TeamSelection() {
  const navigate = useNavigate()
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [open, setOpen] = useState(false)
  const dropdownRef = useRef<HTMLDivElement>(null)

  const selectedTeam = selectedId
    ? WORLD_CUP_TEAMS.find(t => t.id === selectedId)
    : null

  /* close dropdown on outside click */
  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setOpen(false)
      }
    }
    document.addEventListener('mousedown', handleClick)
    return () => document.removeEventListener('mousedown', handleClick)
  }, [])

  function handleBack() {
    track('team_selection_back_tapped')
    navigate('/')
  }

  function handleTeamSelect(id: string) {
    track('team_selection_team_selected', { teamId: id })
    setSelectedId(id)
    setOpen(false)
  }

  function handleContinue() {
    if (!selectedId) return
    navigate('/picture', { state: { teamId: selectedId } })
  }

  return (
    <div
      data-page="team-selection"
      className="f-page-enter team-selection-page"
      style={{
        height: '100%',
        width: '100%',
        background: 'var(--f-brand-color-background-default)',
        display: 'flex',
        flexDirection: 'column',
        padding: 'var(--f-brand-space-md)',
        boxSizing: 'border-box',
        overflow: 'hidden',
      }}
    >
      {/* ── Row: Back button + Progress bar ─────────────────────── */}
      <div data-section="header" className="team-selection-header" style={{
        display: 'flex',
        alignItems: 'center',
        gap: 'var(--f-brand-space-md)',
        flexShrink: 0,
      }}>
        <button
          data-ui="back-btn"
          className="team-selection-back-btn"
          onClick={handleBack}
          aria-label="Go back"
          style={{
            width: 'var(--sp-12)',
            height: 'var(--sp-12)',
            borderRadius: 'var(--f-brand-radius-rounded)',
            border: 'none',
            background: 'var(--f-brand-color-background-light)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
            flexShrink: 0,
            WebkitTapHighlightColor: 'transparent',
          }}
        >
          <svg className="team-selection-back-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true">
            <path className="team-selection-back-icon-path" d="M15 19l-7-7 7-7" stroke="var(--f-brand-color-text-default)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>
        <ProgressBar progress={50} />
      </div>

      {/* ── Title ───────────────────────────────────────────────── */}
      <h2 data-section="title" className="team-selection-title" style={{
        font: 'var(--f-brand-type-title-3)',
        color: 'var(--f-brand-color-text-default)',
        textAlign: 'center',
        marginTop: 'var(--f-brand-space-xl)',
        marginBottom: 'var(--f-brand-space-xl)',
      }}>
        Select your team
      </h2>

      {/* ── Dropdown ────────────────────────────────────────────── */}
      <div data-section="team-dropdown" className="team-selection-dropdown" ref={dropdownRef} style={{ position: 'relative', flexShrink: 0 }}>
        {/* Trigger input */}
        <button
          data-ui="team-dropdown-btn"
          className="team-selection-dropdown-btn"
          onClick={() => setOpen(prev => !prev)}
          aria-haspopup="listbox"
          aria-expanded={open}
          style={{
            width: '100%',
            height: 'var(--sp-12)',
            background: 'var(--f-brand-color-background-light)',
            border: '1px solid var(--f-brand-color-border-default)',
            borderRadius: 'var(--f-brand-radius-base)',
            padding: '0 var(--f-brand-space-md)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            cursor: 'pointer',
            font: 'var(--f-brand-type-body)',
            color: selectedTeam ? 'var(--f-brand-color-text-default)' : 'var(--f-brand-color-text-subtle)',
            WebkitTapHighlightColor: 'transparent',
          }}
        >
          <span className="team-selection-dropdown-label">{selectedTeam ? selectedTeam.name : 'Select a team'}</span>
          <svg
            className="team-selection-dropdown-chevron"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            aria-hidden="true"
            style={{
              flexShrink: 0,
              transform: open ? 'rotate(180deg)' : 'rotate(0deg)',
              transition: `transform var(--f-brand-motion-duration-instant) var(--f-brand-motion-easing-exit)`,
            }}
          >
            <path className="team-selection-dropdown-chevron-path" d="M6 9l6 6 6-6" stroke="var(--f-brand-color-text-subtle)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>

        {/* Listbox */}
        {open && (
          <ul
            className="team-selection-dropdown-list"
            role="listbox"
            style={{
              position: 'absolute',
              top: 'calc(100% + var(--f-brand-space-xs))',
              left: 0,
              right: 0,
              background: 'var(--f-brand-color-background-light)',
              borderRadius: 'var(--f-brand-radius-base)',
              boxShadow: '0px 2px 4px 2px var(--f-brand-shadow-medium)',
              padding: '0 var(--f-brand-space-md)',
              maxHeight: 280,
              overflowY: 'auto',
              zIndex: 10,
              listStyle: 'none',
              margin: 0,
              scrollbarWidth: 'thin',
              scrollbarColor: 'var(--f-brand-color-text-muted) transparent',
            }}
          >
            {WORLD_CUP_TEAMS.map((team, i) => (
              <li
                className="team-selection-dropdown-item"
                key={team.id}
                role="option"
                aria-selected={team.id === selectedId}
                onClick={() => handleTeamSelect(team.id)}
                style={{
                  padding: 'var(--f-brand-space-md) 0',
                  borderBottom: i < WORLD_CUP_TEAMS.length - 1
                    ? '1px solid var(--f-brand-color-background-default)'
                    : 'none',
                  font: 'var(--f-brand-type-body)',
                  color: 'var(--f-brand-color-text-default)',
                  cursor: 'pointer',
                  WebkitTapHighlightColor: 'transparent',
                }}
              >
                {team.name}
              </li>
            ))}
          </ul>
        )}
      </div>

      {/* ── Spacer ──────────────────────────────────────────────── */}
      <div className="team-selection-spacer" style={{ flex: 1 }} />

      {/* ── "Already have a card? Log in" ───────────────────────── */}
      <p className="team-selection-login-prompt" style={{
        textAlign: 'center',
        font: 'var(--f-brand-type-headline)',
        color: 'var(--f-brand-color-text-default)',
        marginBottom: 'var(--f-brand-space-md)',
        flexShrink: 0,
      }}>
        Already have a card?{' '}
        <span className="team-selection-login-link" style={{ fontWeight: 'var(--weight-med)' }}>Log in</span>
      </p>

      {/* ── Continue button ─────────────────────────────────────── */}
      <button
        data-section="confirm-cta"
        data-ui="continue-btn"
        className="team-selection-continue-btn"
        onClick={handleContinue}
        disabled={!selectedId}
        style={{
          width: '100%',
          height: 'var(--sp-14)',
          borderRadius: 'var(--f-brand-radius-rounded)',
          border: 'none',
          background: 'var(--f-brand-color-primary)',
          color: 'var(--f-brand-color-background-light)',
          font: 'var(--f-brand-type-body-medium)',
          cursor: selectedId ? 'pointer' : 'default',
          opacity: selectedId ? 1 : 0.5,
          transition: `opacity var(--f-brand-motion-duration-instant) var(--f-brand-motion-easing-exit)`,
          flexShrink: 0,
          WebkitTapHighlightColor: 'transparent',
        }}
      >
        Add your photo
      </button>
    </div>
  )
}
