// src/angular/components/button/button.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  booleanAttribute,
} from '@angular/core';

type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'white-outlined' | 'white-filled';
type ButtonSize = 'default' | 'sm' | 'lg';

@Component({
  selector: 'app-button',
  standalone: true,
  templateUrl: './button.component.html',
  styleUrl: './button.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ButtonComponent {
  @Input() variant: ButtonVariant = 'primary';
  @Input() size: ButtonSize = 'default';
  @Input({ transform: booleanAttribute }) fullWidth = false;
  @Input({ transform: booleanAttribute }) loading = false;
  @Input({ transform: booleanAttribute }) disabled = false;
  @Input() className = '';
  @Input() type: 'button' | 'submit' | 'reset' = 'button';

  @Output() clicked = new EventEmitter<MouseEvent>();

  get isDisabled(): boolean {
    return this.disabled || this.loading;
  }

  get classList(): string[] {
    return [
      'f-button',
      this.variant !== 'primary' ? `f-button--${this.variant}` : '',
      this.size !== 'default' ? `f-button--${this.size}` : '',
      this.fullWidth ? 'f-button--full-width' : '',
      this.className,
    ].filter(Boolean);
  }

  onButtonClick(event: MouseEvent): void {
    if (this.isDisabled) {
      event.preventDefault();
      event.stopPropagation();
      return;
    }

    this.clicked.emit(event);
  }
}

<button
  [class]="classList.join(' ')"
  [attr.data-component]="'button'"
  [type]="type"
  [disabled]="isDisabled"
  [attr.aria-disabled]="isDisabled ? true : null"
  [attr.aria-busy]="loading ? true : null"
  (click)="onButtonClick($event)"
>
  @if (loading) {
    <span class="f-button__spinner" aria-hidden="true"></span>
  } @else {
    <span class="f-button__icon" aria-hidden="true">
      <ng-content select="[icon-left]"></ng-content>
    </span>
  }

  <ng-content></ng-content>

  @if (!loading) {
    <span class="f-button__icon" aria-hidden="true">
      <ng-content select="[icon-right]"></ng-content>
    </span>
  }
</button>

// src/components/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react'
import '../styles/fds-button.css'

type Variant = 'primary' | 'secondary' | 'ghost' | 'white-outlined' | 'white-filled'
type Size = 'default' | 'sm' | 'lg'

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: Variant
  size?: Size
  fullWidth?: boolean
  iconLeft?: ReactNode
  iconRight?: ReactNode
  loading?: boolean
}

export default function Button({
  variant = 'primary',
  size = 'default',
  fullWidth = false,
  iconLeft,
  iconRight,
  loading = false,
  disabled,
  children,
  className,
  ...props
}: ButtonProps) {
  const classes = [
    'f-button',
    variant !== 'primary' ? `f-button--${variant}` : '',
    size !== 'default' ? `f-button--${size}` : '',
    fullWidth ? 'f-button--full-width' : '',
    className ?? '',
  ]
    .filter(Boolean)
    .join(' ')

  const isDisabled = disabled || loading

  return (
    <button className={classes}
      {...props}
      data-component="button"
      disabled={isDisabled}
      aria-disabled={isDisabled || undefined}
      aria-busy={loading || undefined}
    >
      {loading ? (
        <span className="f-button__spinner" aria-hidden="true" />
      ) : (
        iconLeft && <span className="f-button__icon" aria-hidden="true">{iconLeft}</span>
      )}
      {children}
      {!loading && iconRight && (
        <span className="f-button__icon" aria-hidden="true">{iconRight}</span>
      )}
    </button>
  )
}
