// src/components/Spinner.tsx
interface SpinnerProps {
  fullScreen?: boolean
  size?: number
}

export default function Spinner({ fullScreen = false, size = 32 }: SpinnerProps) {
  const spinner = (
    <svg className="f-spinner"
      data-component="spinner"
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      aria-label="Loading"
    >
      <circle className="spinner-track" cx="12" cy="12" r="10" stroke="var(--f-brand-color-border-default)" strokeWidth="3" />
      <path className="spinner-arc"
        d="M12 2a10 10 0 0 1 10 10"
        stroke="var(--f-brand-color-primary)"
        strokeWidth="3"
        strokeLinecap="round"
      />
    </svg>
  )

  if (!fullScreen) return spinner

  return (
    <div className="f-spinner--fullscreen" data-component="spinner">
      {spinner}
      <span className="f-spinner__label">
        FIFA Fan Zone
      </span>
    </div>
  )
}

// src/angular/components/spinner/spinner.component.ts
import { CommonModule } from '@angular/common'
import { Component, Input } from '@angular/core'

@Component({
  selector: 'ffz-spinner',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './spinner.component.html',
})
export class SpinnerComponent {
  @Input() fullScreen = false
  @Input() size = 32
}

<ng-container *ngIf="!fullScreen; else fullScreenTemplate">
  <svg
    class="f-spinner"
    data-component="spinner"
    [attr.width]="size"
    [attr.height]="size"
    viewBox="0 0 24 24"
    fill="none"
    aria-label="Loading"
  >
    <circle class="spinner-track" cx="12" cy="12" r="10" stroke="var(--f-brand-color-border-default)" stroke-width="3" />
    <path
      class="spinner-arc"
      d="M12 2a10 10 0 0 1 10 10"
      stroke="var(--f-brand-color-primary)"
      stroke-width="3"
      stroke-linecap="round"
    />
  </svg>
</ng-container>

<ng-template #fullScreenTemplate>
  <div class="f-spinner--fullscreen" data-component="spinner">
    <svg
      class="f-spinner"
      [attr.width]="size"
      [attr.height]="size"
      viewBox="0 0 24 24"
      fill="none"
      aria-label="Loading"
    >
      <circle class="spinner-track" cx="12" cy="12" r="10" stroke="var(--f-brand-color-border-default)" stroke-width="3" />
      <path
        class="spinner-arc"
        d="M12 2a10 10 0 0 1 10 10"
        stroke="var(--f-brand-color-primary)"
        stroke-width="3"
        stroke-linecap="round"
      />
    </svg>
    <span class="f-spinner__label">
      FIFA Fan Zone
    </span>
  </div>
</ng-template>
